---

# This is the string configuration file for English.
en-GB:
  
  # groove 008
  groove_name_008: Marked Prey
  groove_name_all_caps_groove_008: MARKED PREY
  groove_description_008: "Killllll the weeeeeeaaak."

  # groove 020
  groove_name_008: Effigy
  groove_name_all_caps_groove_008: EFFIGY
  groove_description_008: "Eye for an eye"
  
...